/* eslint-disable */
// This file was generated by [specta](https://github.com/oscartbeaumont/specta). Do not edit this file manually.

/**
 * Represents the user's intent for the citation style they are building.
 * This struct captures the state of the "Decision Wizard" and is used
 * to generate the next set of questions or the final CSL style.
 */
export type StyleIntent = { base_archetype: string | null; class: CitationClass | null; author_format: NameOptions | null; has_bibliography: boolean | null };

export type CitationClass = "InText" | "Note" | "Numeric";

export type NameOptions = { form: NameForm; et_al: EtAlConfig | null };

export type NameForm = "Long" | "Short";

export type EtAlConfig = { min: number; use_first: number };

/**
 * A package returned by the backend containing everything the frontend
 * needs to render the next step in the wizard.
 */
export type DecisionPackage = { missing_fields: string[]; question: Question | null; previews: Preview[]; preview_html: string };

export type Question = { id: string; text: string; description: string | null };

export type Preview = { label: string; html: string; choice_value: any };
